export { Header } from "./header"
export { Hero } from "./hero"
export { FindContactHero } from "./find-contact-hero"
export type { ContactPerson } from "./find-contact-hero"
export { HowItWorks } from "./how-it-works"
export { Features } from "./features"
export { Pricing } from "./pricing"
export { Testimonials } from "./testimonials"
export { Cta } from "./cta"
export { Footer } from "./footer"
export { BackgroundDecor } from "./background-decor"
